### ISSUE TITLE
好耶！

### ISSUE THREAD

**Issue by Alex-WU-Gen-9-png** [TimFang4162/desktop-schedule#1]
真不错！（虽然晚了2年才看到
Fang还在开发吗 之前Mark有提到过
（从arkerny那里来的 你是唯一的follower
- - -
This is not an issue, please ignore.

**Comment by arkerny** [comment]
> 真不错！（虽然晚了2年才看到 Fang还在开发吗 之前Mark有提到过 （从arkerny那里来的 你是唯一的follower
> 
> This is not an issue, please ignore.

就是说arkerny本人不知道这是哪位（
现在arkerny打算加入开发了但是估计学业问题没啥空

**Comment by arkerny** [comment]
没有其他事情了的话我 Close 了

**Comment by TimFang4162** [comment]
> 

会一直维护此项目，未来将会用tarui+vue3+naiveui重构，感谢各位支持:D
